### ISSUE TITLE
Ausencia clase de hoy

### ISSUE THREAD

**Issue by florbril** [CodingCarlos/Curso-JS-para-desarrolladores-web_ed10#13]
Hola Carlos! hoy no puedo ir al curso :( , podrías grabar la clase como hiciste con Bea la semana pasada?? gracias y buen finde!

**Comment by CodingCarlos** [comment]
Acabo de ver el issue :( 

Hoy la clase ha sido tranquilita, y no hay ejercicios nuevos. Échale un ojo a los callbacks, y el lunes le doy un repaso, y en la práctica me siento contigo a verlo en un momento
